# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from delos.protos.cartpole import env_pb2 as delos_dot_protos_dot_cartpole_dot_env__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in delos/protos/cartpole/env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CartPoleServiceStub(object):
    """----------------------------
    Service
    ----------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnvStream = channel.stream_stream(
                '/gym.cartpole.v1.CartPoleService/EnvStream',
                request_serializer=delos_dot_protos_dot_cartpole_dot_env__pb2.EnvRequest.SerializeToString,
                response_deserializer=delos_dot_protos_dot_cartpole_dot_env__pb2.EnvResponse.FromString,
                _registered_method=True)


class CartPoleServiceServicer(object):
    """----------------------------
    Service
    ----------------------------
    """

    def EnvStream(self, request_iterator, context):
        """Bidirectional stream. The first message sent by the client SHOULD be a Reset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartPoleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnvStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EnvStream,
                    request_deserializer=delos_dot_protos_dot_cartpole_dot_env__pb2.EnvRequest.FromString,
                    response_serializer=delos_dot_protos_dot_cartpole_dot_env__pb2.EnvResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gym.cartpole.v1.CartPoleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gym.cartpole.v1.CartPoleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CartPoleService(object):
    """----------------------------
    Service
    ----------------------------
    """

    @staticmethod
    def EnvStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gym.cartpole.v1.CartPoleService/EnvStream',
            delos_dot_protos_dot_cartpole_dot_env__pb2.EnvRequest.SerializeToString,
            delos_dot_protos_dot_cartpole_dot_env__pb2.EnvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
