"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
CartPole-v1 streaming control protocol (Python-focused)
Bidirectional streaming: a client sends commands (reset/step/close)
and receives environment results as a stream. No rendering.

Generate Python code (requires grpcio-tools):
  python -m grpc_tools.protoc -I . \\
      --python_out=. --pyi_out=. --grpc_python_out=. cartpole_stream.proto

CartPole-v1 specifics:
  - Observation shape: [4] (float32)
  - Action space: Discrete{2} (0 = push left, 1 = push right)
  - Gymnasium-style termination flags: terminated, truncated
"""

import abc
import collections.abc
import delos.protos.cartpole.env_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class CartPoleServiceStub:
    """----------------------------
    Service
    ----------------------------
    """

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    EnvStream: grpc.StreamStreamMultiCallable[
        delos.protos.cartpole.env_pb2.EnvRequest,
        delos.protos.cartpole.env_pb2.EnvResponse,
    ]
    """Bidirectional stream. The first message sent by the client SHOULD be a Reset."""

class CartPoleServiceAsyncStub:
    """----------------------------
    Service
    ----------------------------
    """

    EnvStream: grpc.aio.StreamStreamMultiCallable[
        delos.protos.cartpole.env_pb2.EnvRequest,
        delos.protos.cartpole.env_pb2.EnvResponse,
    ]
    """Bidirectional stream. The first message sent by the client SHOULD be a Reset."""

class CartPoleServiceServicer(metaclass=abc.ABCMeta):
    """----------------------------
    Service
    ----------------------------
    """

    @abc.abstractmethod
    def EnvStream(
        self,
        request_iterator: _MaybeAsyncIterator[delos.protos.cartpole.env_pb2.EnvRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[delos.protos.cartpole.env_pb2.EnvResponse], collections.abc.AsyncIterator[delos.protos.cartpole.env_pb2.EnvResponse]]:
        """Bidirectional stream. The first message sent by the client SHOULD be a Reset."""

def add_CartPoleServiceServicer_to_server(servicer: CartPoleServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
